<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kbot">

  <xacro:include filename="$(find chefbot_description)/urdf/properties.xacro" />
  <xacro:include filename="$(find chefbot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find chefbot_description)/urdf/kbot_macros.xacro" />
  <xacro:if value="${gazebo == 'true'}">
    <xacro:include filename="$(find chefbot_description)/urdf/kbot.gazebo" />
  </xacro:if>

  <!-- The physic engine does not accept a base_link with inertia. It is then useful to
       add a simple link without inertia and make a joint between it and the chassis
    -->

  <link name="base_footprint">
    <xacro:box_inertia m="0.001" w="0.001" h="0.001" d="0.001" />
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.04" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
      <material name="gold" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 ${(2*wheel_radius)}" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <xacro:wheel prefix="left" y_reflect="1" />
  <xacro:wheel prefix="right" y_reflect="-1" />

  <xacro:caster prefix="front" x_reflect="1" />
  <!-- it will be easy to know which direction is front in rviz
  <xacro:caster prefix="rear" x_reflect="-1" />
  -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}" />
      </geometry>
      <material name="blue" />
    </visual>
  </link>
  <joint name="lidar_joint" type="fixed">
    <origin xyz="0 0 ${3.1*2*wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="lidar_link" />
  </joint>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 0.02 0.001" />
      </geometry>
      <material name="green" />
    </visual>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.035 0.03 0.01" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>


  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}" />
      </geometry>
      <material name="red" />
    </visual>

    <xacro:box_inertia m="${cameraMass}" w="${cameraSize}" h="${cameraSize}" d="${cameraSize}" />

  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_link" />
    <origin rpy="0 0 0" xyz="0.09 0.0 0.12" />
    <axis xyz="1 0 0" />
  </joint>

</robot>