joint_limits:
  right_wheel_joint:  
    has_velocity_limits: true
    max_velocity: 0.05
    min_velocity: -0.05 # m/s
    has_acceleration_limits: true
    max_acceleration: 0.01
    min_acceleration: -0.01 # m/s^2
    has_jerk_limits: true
    max_jerk: 0.02 # m/s^3
    has_effort_limits: true
    max_effort: 200
    min_effort: -200

  left_wheel_joint:   
    has_velocity_limits: true
    max_velocity: 0.05
    min_velocity: -0.05 # m/s
    has_acceleration_limits: true
    max_acceleration: 0.1
    min_acceleration: -0.01 # m/s^2
    has_jerk_limits: true
    max_jerk: 0.02
    has_effort_limits: true
    max_effort: 200
    min_effort: -200
