joint_limits:
  right_wheel_joint:    
    has_position_limits: false
    min_position: 0.0
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: true
    max_effort: 255
    min_effort: -255

  left_wheel_joint:
    has_position_limits: false
    min_position: 0.0
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: true
    max_effort: 255
    min_effort: -255
