footprint: [[-0.101, -0.101], [-0.101, 0.101], [0.101, 0.101], [0.101, -0.101]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2
publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.02

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser
    laser: {sensor_frame: lidar_link, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation_g:
    inflation_radius: 0.06
    
inflation_l:
    # inflation_radius: 0.03
    inflation_radius: 1.75    
    cost_scaling_factor: 2.58
