# don't change it. everything here are correct.

global_frame: map
rolling_window: false
track_unknown_space: true
width: 4
height: 8

plugins:
  - {name: static,  type: "costmap_2d::StaticLayer"}
  - {name: inflation_g, type: "costmap_2d::InflationLayer"}
  - {name: obstacle_layer,   type: "costmap_2d::VoxelLayer"}
