global_frame: odom
rolling_window: true
static_map: false
# area of local map window
width: 2
height: 2

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,    type: "costmap_2d::InflationLayer"}
