# footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]]
robot_radius: 0.12
footprint_padding: 0.01
map_type: costmap
robot_base_frame: base_footprint
update_frequency: 2.0
publish_frequency: 1.0
# tolerance of relative coordinate conversion time between tf
transform_tolerance: 0.5

resolution: 0.05
# local costmap displays obstacle 2.5m away max.

#obstacle_range: 2.5
#raytrace_range: 3.0
# visualize_potential: true

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    enable: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 1.0
    min_obstacle_height: 0.0
    observation_sources: laser
    laser: {sensor_frame: lidar_link, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

#inflation:
    #enabled: true
    # inflation_radius: 0.03
    #inflation_radius: 1.75
    #inflation_radius: 0.06       
    #cost_scaling_factor: 2.58

    # exp(-1.0 * cost_scaling_factor *(distance_from_obstacle - inscribed_radius)) *(254 - 1)
    #cost_scaling_factor: 0.5

inflation_g:
    inflation_radius: 0.11
    cost_scaling_factor: 5
    
inflation_l:    
    inflation_radius: 0.04
    cost_scaling_factor: 3

