# don't change it. good enough!

global_frame: map
update_frequency: 1.0
static_map: true
rolling_window: false
track_unknown_space: true
width: 8
height: 8
# resolution: 0.05

plugins:
  - {name: static,          type: "costmap_2d::StaticLayer"}
  - {name: inflation_g,     type: "costmap_2d::InflationLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::VoxelLayer"}
