global_frame: odom
# static_map: false
rolling_window: true
width: 2
height: 2
# resolution: 0.03
# transform_tolerance: 1.0			 # transform tolerance time

plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,       type: "costmap_2d::InflationLayer"}
