global_frame: odom
update_frequency: 5.0
static_map: false
rolling_window: true
width: 2.0
height: 2.0
resolution: 0.03
transform_tolerance: 0.5
planner_frequency: 1.0
planner_patiente: 5.0

plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,       type: "costmap_2d::InflationLayer"}
