global_frame: odom
rolling_window: true
width: 2
height: 2

plugins:
  - {name: obstacle_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
